apiVersion: apps/v1
kind: Deployment

metadata:
  name: pipeline-project

spec:
  replicas: 3

  template:
    spec:
      containers:
        - name: pipeline-project
          image: ghcr.io/your-user/pipeline-project:1.0.0